### ISSUE TITLE
assignops: /= behaves incorrectly with negative number

### ISSUE THREAD

**Issue by ee7** [crashappsec/libcon4m#55]
With:

- libcon4m https://github.com/crashappsec/libcon4m/commit/14604adf6ca68c75a08360129d71beb63571c1d1
- x86_64
- Linux 6.9.6
- clang 17.0.6

### Example

```text
x = 3
x /= -1
print(x)
```

### Expected behavior

Outputs -3.

### Observed behavior

Outputs 0.

**Comment by viega** [comment]
Yes, accidentally used the wrong type on the LHS when accessing the union; fixed in branch.
