### ISSUE TITLE
ci: consider enabling ASan and/or UBSan

### ISSUE THREAD

**Issue by ee7** [crashappsec/libcon4m#63]
Not a high priority ticket - just to track this.

PR https://github.com/crashappsec/libcon4m/pull/60#issue-2385099566 enabled ASan and UBSan for debug builds. But those sanitizers currently produce some errors in CI, and CI currently does a (non-debug) build via `./dev build`.

It'd be nice to enable sanitizers in CI if possible (e.g. if there's no false positive from something that libcon4m is doing with something like the gc).

**Comment by viega** [comment]
You'd have to get the false positives out before you could do this, and it's not clear that it's worth the effort given all the custom memory management.
