### ISSUE TITLE
build: consider suppressing/resolving `-Watomic-alignment` warnings

### ISSUE THREAD

**Issue by ee7** [crashappsec/libcon4m#68]
With:

- libcon4m https://github.com/crashappsec/libcon4m/commit/b4fdc8e2e70b0ef18a554562702e2db1e0c9aff0 (and earlier)
- x86_64
- Linux 6.9.7
- clang 7 or later

or:

- the x86_64 Linux CI environment with clang 18 (see [here](https://github.com/crashappsec/libcon4m/actions/runs/9781989624/job/27007338232#step:8:172))

running `dev build` by default produces about 2200 lines of `-Watomic-alignment` warnings, like:

```
../src/hatrack/hash/crown.c:416:25: warning: large atomic operation may incur significant performance penalty; the access size (16 bytes) exceeds the max lock-free size (8  bytes) [-Watomic-alignment]
  416 |         record        = atomic_read(&cur->record);
      |                         ^
../include/hatrack/hatomic.h:35:24: note: expanded from macro 'atomic_read'
   35 | #define atomic_read(x) atomic_load_explicit(x, memory_order_relaxed)
      |                        ^
/usr/lib/clang/17/include/stdatomic.h:141:30: note: expanded from macro 'atomic_load_explicit'
  141 | #define atomic_load_explicit __c11_atomic_load
      |                              ^
```

I added `-Wno-atomic-alignment` locally when using Clang, but we should either do that in the repo, or otherwise resolve these warnings.

Some context:

- https://gcc.gnu.org/legacy-ml/gcc/2017-01/msg00167.html
- https://gcc.gnu.org/legacy-ml/gcc-patches/2017-01/msg02344.html
- https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80878

https://github.com/crashappsec/libcon4m/blob/b4fdc8e2e70b0ef18a554562702e2db1e0c9aff0/include/hatrack/hatomic.h#L26-L35

https://github.com/crashappsec/libcon4m/blob/b4fdc8e2e70b0ef18a554562702e2db1e0c9aff0/include/hatrack/hatomic.h#L40-L50

https://github.com/crashappsec/libcon4m/blob/b4fdc8e2e70b0ef18a554562702e2db1e0c9aff0/src/quark/x86_64.s#L6-L19

Where my understanding of the rationale for the last file was, from my Slack messages in January:

- When we compile on x86_64, gcc targets a generic x86_64 CPU by default.
- `cmpxchg16b` isn't technically available on every x86_64 CPU, but the oldest AMD CPU that supports it fully (Phenom X3, K10) is from around 2008.
- Therefore by default, gcc won't lower `__atomic_compare_exchange_16` to `cmpxchg16b`.
- But if we pass e.g. `-march=x86-64-v3` we should see the `cmpxchg16b`.
- However, something similar apparently didn't work for aarch64.
- `__atomic_compare_exchange_16` is supposed to be defined across all sizes, but musl doesn't define it for 128-bit ints.
- So we have asm implementations that are the bare minimum around `cmpxchg16b`.

**Comment by viega** [comment]
There's nothing wrong with that code; it's intentional that we use the emulation where it's not supported in hardware, and it still performs well there; the emulation is not actually particularly slow. 

Feel free to detect x86 and add the flag in the meson build.
